### ISSUE TITLE
Ansible failed to complete successfully: error in MariaDB role: 'dict_values' is undefined

### ISSUE THREAD

**Issue by s-diez** [punktDe/ansible-proserver-template#1]
Hi, I just tried to run this example and there seems to be some incompatibility between the used version of the role mariadb.

Running `vagrant up` on a clean checkout results in the following error for me:

```
TASK [mariadb : Create databases] **********************************************
fatal: [proserver-dev]: FAILED! => {"msg": "The conditional check 'item' failed. The error was: error while evaluating conditional (item): 'dict_values' is undefined\n\nThe error appears to have been in '/PROJECT_PATH/roles/mariadb/tasks/databases.yaml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Create databases\n  ^ here\n"}
	to retry, use: --limit @/PROJECT_PATH/playbook.retry

PLAY RECAP *********************************************************************
proserver-dev              : ok=7    changed=5    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

Changing the commit of the submodule of the mariadb role from https://github.com/punktDe/proserver-ansible-mariadb/commit/86589032a007fa1d2240b66216ce2b143f3cebc7#diff-2cb1ad4f3eb0ea704c74a73689ad1654 to https://github.com/punktDe/proserver-ansible-mariadb/commit/859f217acd73e516445ab101b70c042a55843c89#diff-2cb1ad4f3eb0ea704c74a73689ad1654 resolved the issue.

I did no further testing if later commits would still work.

Maybe you could review the submodules and update them if possible. Thanks for the example and test setup.

**Comment by fnkr** [comment]
Hi @s-diez,

I have updated the playbook and documentation to match recent changes. Ansible should now complete successfully. Please update your repository and submodules and let me know if this works for you.

```sh
git pull
git submodule update --init
vagrant destroy -f
vagrant up --provision
```

Note: Please use Python 3 to run this playbook. If your system-wide installation of Ansible uses Python 2 you can use venv:

```sh
python3 -m venv venv
venv/bin/pip install ansible
export PATH="$PWD/venv/bin:$PATH"
vagrant up --provision
```

**Comment by s-diez** [comment]
Hi @fnkr 
Thanks for the general update.
Everything seems to work with the current state.

**Comment by fnkr** [comment]
Please let me know if you have any further questions!
